"""Pydantic schemas and dataclasses for agents."""

import time
from dataclasses import dataclass
from typing import Any, List, Optional
from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """A single step within an execution plan."""
    id: int = Field(description="1-based step number")
    tool: str = Field(description="One of: code_exec, search, calculator, get_weather")
    args_json: str = Field(
        description="JSON object string with tool arguments. May contain '{step_N_result}'."
    )
    description: str = Field(description="What this step accomplishes")


class Plan(BaseModel):
    """The structured sequence of tool steps formulated by the planner."""
    steps: List[PlanStep]


class Synthesis(BaseModel):
    """The synthesis evaluation and final response generated by the agent."""
    answer: str
    done: bool = True
    extra_steps: List[PlanStep] = Field(default_factory=list)


@dataclass
class Usage:
    """Token and call count tracker for LLM interactions."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    llm_calls: int = 0

    def add(self, prompt: int = 0, completion: int = 0, calls: int = 1) -> None:
        self.prompt_tokens += prompt or 0
        self.completion_tokens += completion or 0
        self.llm_calls += calls or 0


def make_result(
    mode: str,
    query: str,
    answer: str,
    trace: list,
    usage: Usage,
    started: float,
    plan: Optional[list] = None,
    error: Optional[str] = None,
) -> dict[str, Any]:
    """Format the standard result dictionary returned by both agent modes."""
    return {
        "success": error is None,
        "mode": mode,
        "query": query,
        "answer": answer,
        "plan": plan,
        "trace": trace,
        "error": error,
        "usage": {
            "prompt_tokens": usage.prompt_tokens,
            "completion_tokens": usage.completion_tokens,
            "total_tokens": usage.prompt_tokens + usage.completion_tokens,
            "llm_calls": usage.llm_calls,
            "elapsed": round(time.time() - started, 2),
        },
    }
